<div align="center">

  <div class="page-title">
      <h1 style="text-align: center;">Your Payment is Processed</h1>
  </div>

<h2 style="text-align: center;">We are Redirecting You to The Payment Page</h2>
<p style="text-align: center;">Your Order # is: <b><?= $this->getOrderId(); ?></b></p>
<p style="text-align: center;">Please Do Not <b>Close</b>, <b>Refresh</b>,or click <b>Back</b> on this page</p>
<p><?= $this->getError(); ?> </p>
</div>

<iframe id="sgoplus-iframe" src="" scrolling="no" allowtransparency="true" frameborder="0" height="300"></iframe>

<script type="text/javascript" src="https://sandbox-kit.espay.id/public/signature/js"></script>
<script type="text/javascript">

      window.onload = function () {
           var key = '<?= $this->getKey(); ?>';
           var payid = '<?= $this->getOrderId(); ?>';
           var backurl = '<?= $this->getBackUrl(); ?>';
           var bankCode = '<?= $this->getBankCode(); ?>';
           var productCode = '<?= $this->getProductCode(); ?>';

           var data = {
               /**
                * display available : option, select (default)
                */
               display: 'select',
               paymentId: payid,
               bankCode: bankCode,
               bankProduct: productCode,
               key: key,
               backUrl: encodeURIComponent(backurl),
           },
                   sgoPlusIframe = document.getElementById("sgoplus-iframe");
           if (sgoPlusIframe !== null) {
               sgoPlusIframe.src = SGOSignature.getIframeURL(data);
           }
           SGOSignature.receiveForm();
         };
</script>
