INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_bcaatm', 'ESPay BCA VA Online');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_bcaklikpay', 'ESPay BCA KlikPay');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_xltunai', 'ESPay XL TUNAI');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_biiatm', 'ESPay ATM MULTIBANK');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_bnidbo', 'ESPay BNI Debit Online');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_epaybri', 'ESPay e-Pay BRI');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_briatm', 'ESPay BRI ATM');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_danamonob', 'ESPay Danamon Online Banking');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_danamonatm', 'ESPay ATM Danamon');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_dkiib', 'ESPay DKI IB');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_mandirisms', 'ESPay MANDIRI SMS');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_finpay195', 'ESPay Modern Channel');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_mandiriecash', 'ESPay MANDIRI E-CASH');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_creditcard', 'ESPay Credit Card Visa / Master');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_mandiriib', 'ESPay MANDIRI IB');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_maspionatm', 'ESPay ATM MASPION');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_mayapadaib', 'ESPay Mayapada Internet Banking');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_muamalatatm', 'ESPay MUAMALAT ATM');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_nobupay', 'ESPay Nobu Pay');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_permataatm', 'ESPay PERMATA ATM');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_permatapeb', 'ESPay Permata ebusiness');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_permatanetpay', 'ESPay PermataNet');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_emoedikk2', 'ESPay EMOEDIKK2');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('accpt_espay_emoedikk', 'ESPay EMOEDIKK');
INSERT INTO `sales_order_status` (`status`, `label`) VALUES ('payment_accepted_espay', 'ESPay Payment');
